FROM python:3.11.9
WORKDIR .
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
# Uncomment the following line. Add the desired values.
# CMD ["python", "main.py", "--test", "True", "--debug", "True", "--dbpass", "changethispassword"]
