FROM python:3.10
WORKDIR .
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
# Uncomment the following line. Add the desired values.
# CMD ["python", "main.py", "--debug", "True", "--mode", "self", "--dbpass", "changethispassword"]
