# fly.toml app configuration file generated for damp-dust-5880 on 2023-11-18T18:43:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "damp-dust-5880"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = ""
  internal_port = 0
  [services.concurrency]
    hard_limit = 5
    soft_limit = 3

[[vm]]
  size = "shared-cpu-1x"
  memory = "1GB"
  processes = ["app"]
