"""This module contains All the text messages"""
from aiogram import md


class Text:
    """Contains the text to be displayed for the bot commands"""

    save_lang_text_eng = "Language preference is saved 👍"
    save_lang_text_greek = "Η επιλογή γλώσσας αποθηκεύτηκε 👍"
    choose_lang_text = md.escape_md(
        "👋 Hello! Please select your language." "\n👋 Γεια! Διάλεξε τη γλώσσα επιλογής σου"
    )
    help_text_eng = md.text(
        md.bold("\n👇 -- The command list -- 👇\n"),
        "\n• /search or /s ",
        md.escape_md("\n\n\t\t\tArticle search based on a keyword"),
        "\n\n\t\t\tExample:\t/search ΒΙΟΜΕ",
        "\n",
        "\n• /category or /c  ",
        md.escape_md("\n\n\t\t\tSearch the latest news of the category"),
        md.escape_md("\n\n\t\t\tExample:\t/category Newsroom"),
        md.escape_md("\n\t\t\tExample:\t/category news"),
        md.escape_md("\n\n\t\t\tValid categories:"),
        md.escape_md("\n\t\t\t\t\t\tNews[room]"),
        md.escape_md("\n\t\t\t\t\t\tGre[ece]"),
        md.escape_md("\n\t\t\t\t\t\tPol[itics]"),
        md.escape_md("\n\t\t\t\t\t\tEco[nomy]"),
        md.escape_md("\n\t\t\t\t\t\tInter[national]"),
        md.escape_md("\n\t\t\t\t\t\tRepo[rtage]"),
        md.escape_md("\n\t\t\t\t\t\tAna[lysis]"),
        md.escape_md("\n\t\t\t\t\t\tCul[ture]"),
        md.escape_md("\n\t\t\t\t\t\tAnas[kopisi]"),
        md.escape_md("\n\t\t\t\t\t\t[tpp.]radio"),
        md.escape_md("\n\t\t\t\t\t\t[tpp.]tv"),
        md.escape_md("\n"),
        "\n• /language or /lang",
        md.escape_md("\n\n\t\t\tChoose your preferred language"),
        md.escape_md("\n\n• /help : Prints this help text"),
        "\n",
    )
    help_text_eng2 = md.text(
        md.bold("\n👇 -- The newspaper list -- 👇\n"),
        md.escape_md("\n• /efsyn"),
        "\nEfsyn",
        "\n",
        md.escape_md("\n• /kat"),
        "\nKathimerini english version",
        "\n",
        md.escape_md("\n• /tov"),
        "\nTo vima",
        "\n",
        md.escape_md("\n• /ert"),
        "\nErt",
        "\n",
        md.escape_md("\n• /naf"),
        "\nNaftemporiki",
        "\n",
        md.escape_md("\n• /doc"),
        "\nDocumento",
        "\n",
        md.escape_md("\n• /prin"),
        "\nPrin",
        "\n",
        md.escape_md("\n• /ru"),
        "\nReporters United",
        "\n",
        md.escape_md("\n• /kontra"),
        md.escape_md("\nKontra - eksegersi.gr"),
        "\n",
        md.escape_md("\n• /geu"),
        md.escape_md("\nGuardian Europe"),
        "\n",
        md.escape_md("\n• /gme"),
        md.escape_md("\nGuardian Middle East"),
        "\n",
        md.escape_md("\n• /gw"),
        md.escape_md("\nGuardian World"),
        "\n",
        md.escape_md("\n• /reu"),
        md.escape_md("\nReuters"),
        "\n",
        md.escape_md("\n• /rint"),
        md.escape_md("\nReuters International"),
        "\n",
        md.escape_md("\n• /rpol"),
        md.escape_md("\nReuters Politics"),
        "\n",
        md.escape_md("\n• /rnews"),
        md.escape_md("\nReuters News"),
        "\n",
        md.escape_md("\n• /bbcw"),
        md.escape_md("\nBBC World"),
        "\n",
        md.escape_md("\n• /bbctpint"),
        md.escape_md("\nBBC Top stories International"),
        "\n",
        md.escape_md("\n• /bbceu"),
        md.escape_md("\nBBC Europe"),
        "\n",
        md.escape_md("\n• /bbcsc"),
        md.escape_md("\nBBC Science"),
        "\n",
        md.escape_md("\n• /cnn"),
        md.escape_md("\nCNN"),
        "\n",
        md.escape_md("\n• /cnnw"),
        md.escape_md("\nCNN world"),
        "\n",
        md.escape_md("\n• /cnneu"),
        md.escape_md("\nCNN Europe"),
        "\n",
        md.escape_md("\n• /dw"),
        md.escape_md("\nDW"),
        "\n",
        md.escape_md("\n• /dww"),
        md.escape_md("\nDW World"),
        "\n",
        md.escape_md("\n• /dweu"),
        md.escape_md("\nDW Europe"),
        "\n",
        md.escape_md("\n• /dwsc"),
        md.escape_md("\nDW Science"),
        "\n",
        md.escape_md("\n• /dwasia"),
        md.escape_md("\nDW Asia"),
        "\n",
        md.escape_md("\n• /dwenv"),
        md.escape_md("\nDW Enviroment"),
        "\n",
    )
    help_text_eng3 = md.text(
        md.bold("👇 -- Schedule your news -- 👇\n"),
        md.escape_md("\n• /sch <news command> <interval in days>"),
        md.escape_md("\nExample: /sch ert 1"),
        md.escape_md("\n(you will get news every day)"),
        "\n",
        md.escape_md("\n• /sch <news command> <days>"),
        md.escape_md("\nvalid days: mon, tue, wed, thu, fri, sat, sun"),
        md.escape_md("\nExample: /sch ert mon-fri"),
        md.escape_md("\n(you will get news from ert from Monday to Friday)"),
        "\n",
        md.escape_md("\n• /mysch"),
        "\n",
        "Get all your schedules" "\n",
        md.escape_md("\n• /delall"),
        "\n",
        "Deletes ALL your schedules",
        "\n",
        md.escape_md("\n• /del"),
        md.escape_md("\nDeletes a schedule."),
        md.escape_md(
            "\n(Works only if you reply at a message containing a particular schedule from /mysch)"
        ),
    )
    help_text_greek = md.text(
        md.bold("\n👇 -- Η λίστα με όλες τις εντολές -- 👇\n"),
        "\n• /search ή /s ",
        md.escape_md("\n\n\t\t\tΑναζήτηση άρθρων βάσει λέξης κλειδί."),
        "\n\n\t\t\tΠαράδειγμα:\t/search ΒΙΟΜΕ",
        "\n",
        "\n• /category ή /c  ",
        md.escape_md("\n\n\t\t\tΑναζήτηση τελευταίων άρθρων συγκεκριμένης κατηγορίας."),
        md.escape_md("\n\n\t\t\tΠαράδειγμα:\t/category Newsroom"),
        md.escape_md("\n\n\t\t\tΚατηγορίες:"),
        md.escape_md("\n\t\t\t\t\t\tNews[room]"),
        md.escape_md("\n\t\t\t\t\t\tGre[ece]"),
        md.escape_md("\n\t\t\t\t\t\tPol[itics]"),
        md.escape_md("\n\t\t\t\t\t\tEco[nomy]"),
        md.escape_md("\n\t\t\t\t\t\tInter[national]"),
        md.escape_md("\n\t\t\t\t\t\tRepo[rtage]"),
        md.escape_md("\n\t\t\t\t\t\tA[nalysis]"),
        md.escape_md("\n\t\t\t\t\t\tCul[ture]"),
        md.escape_md("\n\t\t\t\t\t\tAnas[kopisi]"),
        md.escape_md("\n\t\t\t\t\t\t[tpp.]radio"),
        md.escape_md("\n\t\t\t\t\t\t[tpp.]tv"),
        md.escape_md("\n"),
        "\n• /language ή /lang",
        md.escape_md("\n\n\t\t\tΔιάλεξε τη γλώσσα της επιλογής σου"),
        md.escape_md("\n\n• /help : Τυπώνει αυτό το βοηθητικό κείμενο"),
        "\n",
    )
    help_text_greek2 = md.text(
        md.bold("\n👇 -- Η λίστα των εφημερίδων -- 👇\n"),
        md.escape_md("\n• /efsyn"),
        md.escape_md("\nΕφημερίδα των Συντακτών (Εφσυν)"),
        "\n",
        md.escape_md("\n• /kat"),
        md.escape_md("\nΚαθημερινή - αγγλική έκδοση"),
        "\n",
        md.escape_md("\n• /tov"),
        "\nΤο Βήμα",
        "\n",
        md.escape_md("\n• /ert"),
        "\nΕρτ",
        "\n",
        md.escape_md("\n• /naf"),
        "\nΝαυτεμπορική",
        "\n",
        md.escape_md("\n• /doc"),
        "\nDocumento",
        "\n",
        md.escape_md("\n• /prin"),
        "\nΠριν",
        "\n",
        md.escape_md("\n• /ru"),
        "\nReporters United",
        "\n",
        md.escape_md("\n• /kontra"),
        md.escape_md("\nΚόντρα - eksegersi.gr"),
        "\n",
        md.escape_md("\n• /geu"),
        md.escape_md("\nGuardian Europe"),
        "\n",
        md.escape_md("\n• /gme"),
        md.escape_md("\nGuardian Middle East"),
        "\n",
        md.escape_md("\n• /gw"),
        md.escape_md("\nGuardian World"),
        "\n",
        md.escape_md("\n• /reu"),
        md.escape_md("\nReuters"),
        "\n",
        md.escape_md("\n• /rint"),
        md.escape_md("\nReuters International"),
        "\n",
        md.escape_md("\n• /rpol"),
        md.escape_md("\nReuters Politics"),
        "\n",
        md.escape_md("\n• /rnews"),
        md.escape_md("\nReuters News"),
        "\n",
        md.escape_md("\n• /bbcw"),
        md.escape_md("\nBBC World"),
        "\n",
        md.escape_md("\n• /bbctpint"),
        md.escape_md("\nBBC Top stories International"),
        "\n",
        md.escape_md("\n• /bbceu"),
        md.escape_md("\nBBC Europe"),
        "\n",
        md.escape_md("\n• /bbcsc"),
        md.escape_md("\nBBC Science"),
        "\n",
        md.escape_md("\n• /cnn"),
        md.escape_md("\nCNN"),
        "\n",
        md.escape_md("\n• /cnnw"),
        md.escape_md("\nCNN world"),
        "\n",
        md.escape_md("\n• /cnneu"),
        md.escape_md("\nCNN Europe"),
        "\n",
        md.escape_md("\n• /dw"),
        md.escape_md("\nDW"),
        "\n",
        md.escape_md("\n• /dww"),
        md.escape_md("\nDW World"),
        "\n",
        md.escape_md("\n• /dweu"),
        md.escape_md("\nDW Europe"),
        "\n",
        md.escape_md("\n• /dwsc"),
        md.escape_md("\nDW Science"),
        "\n",
        md.escape_md("\n• /dwasia"),
        md.escape_md("\nDW Asia"),
        "\n",
        md.escape_md("\n• /dwenv"),
        md.escape_md("\nDW Enviroment"),
        "\n",
    )
    help_text_greek3 = md.text(
        md.bold("👇 -- Φτιάξε το πρόγραμμά σου -- 👇\n"),
        md.escape_md("\n• /sch <εντολή είδησης> <διάστημα σε ημέρες>"),
        md.escape_md("\nΠαράδειγμα: /sch ert 1"),
        md.escape_md("\n(θα λαμβάνετε ειδήσεις της ερτ κάθε 1 ημέρα)"),
        "\n",
        md.escape_md("\n• /sch <εντολή είδησης> <ονόματα ημερών>"),
        md.escape_md("\nΑποδεκτά ονόματα: mon, tue, wed, thu, fri, sat, sun"),
        md.escape_md("\nΠαράδειγμα: /sch ert mon-fri"),
        md.escape_md("\n(Θα λαμβάνετε ειδήσεις της ερτ από Δευτέρα έως Παρασκευή)"),
        "\n",
        md.escape_md("\n• /mysch"),
        "\n",
        "Δείτε το πρόγραμμά σας" "\n",
        md.escape_md("\n• /delall"),
        "\n",
        "Διαγράψτε ό,τι έχετε προγραμματίσει",
        "\n",
        md.escape_md("\n• /del"),
        md.escape_md("\nΔιαγράψτε μια συγκεκριμένη κατηγορία ειδήσεων"),
        md.escape_md(
            "\n(δουλεύει μόνο αν απαντήσετε (reply) σε μήνυμα που περιέχει ένα πρόγραμμα από το /mysch)"
        ),
    )
    to_search_next_page_eng = "Do you want to search the next page?"
    to_search_next_page_greek = "Θέλετε να συνεχίσετε την αναζήτηση στην επόμενη σελίδα;"
    search_next_page_empty_keyword_page_no_1_eng = md.escape_md(
        "Nothing to search." "\nRepeat the search command /search <keyword>"
    )
    search_next_page_empty_keyword_page_no_1_greek = md.escape_md(
        "\nΕπαναλάβετε την αναζήτηση με την εντολή /search " "<λέξη κλειδί>"
    )
